name: .NET Secret

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Environment Secretsprod
      run: |
        echo $TEST_SECUREPROD
      env:
       Test_SECUREPROD: ${{ secrets.PRODUCTIONAWSKEYS }}
