name: .NET Secret

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Environment Secrets
      run: |
        echo $TEST_SECURE
      env:
       Test_SECURE: ${{ secrets.DEVAWSKEYS }}
  
