name: .NET Secret

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Environment Secrets
      run: |
        if [ "$TEST_SECURE" == "MY TEST SECRET GK" ]
        then 
          echo "Got repo Keys"
        fi
      env:
       TEST_SECURE: ${{ secrets.MYTESTSECRETGK }}
  
